games:
  # przykladowa gra, mozna dodawac ile sie chce, "test" w tym przypadku to id mapy ktore jest potrzebne przy tworzeniu tabliczki
  test: # nazwa gry
    lobby:
      world: world
      x: 0
      y: 100
      z: 0
    max-players: 8 # maksymalna ilosc graczy
    start-threshold: 1 # minimalna ilosc graczy do rozpoczecia gry
    arenas: # konfiguracja aren
      punch-the-bats: # nazwa areny
        spawn-location: # polozenie spawnu na arenie dla graczy
          world: world
          x: 1000
          y: 100
          z: 1000
        time: 80 # czas trwania areny w sekundach
        countdown: 10 # czas odliczania do startu areny w sekundach
        data: # dodatkowe informacje o iearenie, sa rozne na kazdej (!)
          bats: 50
          bat-loc-randomize:
            max-x: 4
            max-y: 13
            max-z: 4
          bat-health:
            5: 3
            3: 2
            1: 1
          bat-types:
            5: '&6&l5 punktow' # typ za 10 punktow
            3: '&23 punkty' # typ za 3 punkty
            1: '&81 punkt' # typ za 1 punkt
          bat-chances: # szanse na wystapienie danego nietoperza
            5: 5
            3: 25
            1: 70
      wool-mix-up:
        spawn-location:
          world: world
          x: 2000
          y: 101
          z: 2000
        time: 240
        countdown: 10
        data:
          colors:
            RED: '&4&lCzerwony'
            CYAN: '&3&lCyjankowy'
            PURPLE: '&5&lFioletowy'
            ORANGE: '&6&lPomaranczowy'
            YELLOW: '&e&lZolty'
            BLACK: '&0&lCzarny'
            WHITE: '&f&lBialy'
            GREEN: '&2Zielony'
            BLUE: '&1&lNiebieski'
            LIME: '&a&lLimonkowy'
          disqualify-data:
            min-y: 10
            max-y: 25
            spawn-y: 15
          baseTime: 10
          locations:
            min:
              x: 1960
              y: 100
              z: 1960
            max:
              x: 2040
              y: 100
              z: 2040
      trampolinio:
        spawn-location:
          world: world
          x: 1500
          y: 100
          z: 1500
        time: 20
        countdown: 10
        data:
          radius: 6
          target: 15
          info:
            booster:
              chance: 10
              height:
                min: 1
                max: 3
              title: '&f&lBooster'
            high:
              chance: 20
              height:
                min: 5
                max: 7
              title: '&c&l+10 pkt'
            medium:
              chance: 30
              height:
                min: 2
                max: 4
              title: '&6&l+3 pkt'
            low:
              chance: 40
              height:
                min: 1
                max: 3
              title: '&a&l+1 pkt'